# Generated by Django 4.2.27 on 2025-12-11 17:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "onet_soc_code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "job_zone",
                    models.PositiveSmallIntegerField(help_text="Complexity level 1-5"),
                ),
                ("last_synced", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "occupations",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "element_id",
                    models.CharField(
                        help_text="O*NET element ID", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("knowledge", "Knowledge"),
                            ("skill", "Skill"),
                            ("ability", "Ability"),
                            ("tool", "Tool/Technology"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "parent_skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "db_table": "skills",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="TitleAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alias", models.CharField(db_index=True, max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("onet", "O*NET"),
                            ("lightcast", "Lightcast"),
                            ("manual", "Manual"),
                            ("ai_generated", "AI Generated"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "canonical_occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="skills.occupation",
                    ),
                ),
            ],
            options={
                "db_table": "title_aliases",
                "indexes": [
                    models.Index(fields=["alias"], name="title_alias_alias_f6e59f_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PromotionPath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        help_text="How common this transition is"
                    ),
                ),
                ("sector", models.CharField(blank=True, max_length=100)),
                (
                    "region",
                    models.CharField(
                        blank=True, help_text="US, UK, global, etc.", max_length=50
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Confidence in this path 0.00-1.00",
                        max_digits=3,
                    ),
                ),
                (
                    "source_occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths_from",
                        to="skills.occupation",
                    ),
                ),
                (
                    "target_occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths_to",
                        to="skills.occupation",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_paths",
                "ordering": ["-frequency"],
                "unique_together": {
                    ("source_occupation", "target_occupation", "sector", "region")
                },
            },
        ),
        migrations.CreateModel(
            name="OccupationSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "importance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importance rating 1.00-5.00",
                        max_digits=3,
                    ),
                ),
                (
                    "level",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Required level 1.00-7.00",
                        max_digits=3,
                    ),
                ),
                (
                    "occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupation_skills",
                        to="skills.occupation",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupation_skills",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "db_table": "occupation_skills",
                "ordering": ["-importance"],
                "unique_together": {("occupation", "skill")},
            },
        ),
    ]
