# Generated by Django 4.2.27 on 2025-12-11 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "situation",
                    models.TextField(blank=True, help_text="Optional context"),
                ),
                ("action", models.TextField(help_text="What they did")),
                ("result", models.TextField(blank=True, help_text="Outcome/impact")),
                ("date", models.DateField(blank=True, null=True)),
                ("ai_enhanced_version", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence",
                        to="skills.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Evidence",
                "db_table": "evidence",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckinLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("skipped", models.BooleanField(default=False)),
                ("wins_added", models.PositiveSmallIntegerField(default=0)),
                ("skills_updated", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "readiness_score_snapshot",
                    models.PositiveSmallIntegerField(null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "checkin_logs",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(
                        help_text="Denormalized skill name, especially for custom skills",
                        max_length=200,
                    ),
                ),
                (
                    "proficiency",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Rarely"), (2, "Sometimes"), (3, "Regularly")]
                    ),
                ),
                ("is_custom", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_ratings",
                        to="skills.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_skills",
                "unique_together": {("user", "skill")},
            },
        ),
        migrations.CreateModel(
            name="GapAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "readiness_score",
                    models.PositiveSmallIntegerField(help_text="0-100"),
                ),
                (
                    "strengths",
                    models.JSONField(
                        default=list, help_text="List of skill IDs user has"
                    ),
                ),
                (
                    "gaps",
                    models.JSONField(
                        default=list, help_text="List of {skill_id, priority} objects"
                    ),
                ),
                (
                    "partial_matches",
                    models.JSONField(
                        default=list, help_text="List of skill IDs user is building"
                    ),
                ),
                (
                    "target_occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap_analyses",
                        to="skills.occupation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Gap analyses",
                "db_table": "gap_analyses",
                "unique_together": {("user", "target_occupation")},
            },
        ),
    ]
