# Generated by Django 4.2.27 on 2026-01-05 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInteractionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("title_interpretation", "Title Interpretation"),
                            ("evidence_enhancement", "Evidence Enhancement"),
                            ("gap_coaching", "Gap Coaching"),
                            ("doc_generation", "Document Generation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "input_hash",
                    models.CharField(
                        help_text="SHA256 hash of input for privacy", max_length=64
                    ),
                ),
                ("tokens_input", models.PositiveIntegerField()),
                ("tokens_output", models.PositiveIntegerField()),
                ("model_used", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_interaction_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
