# Generated by Django 4.2.27 on 2025-12-11 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("formal", "Formal"),
                            ("conversational", "Conversational"),
                            ("concise", "Concise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("audience", models.CharField(blank=True, max_length=50)),
                ("content_markdown", models.TextField()),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_documents",
                        to="skills.occupation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "generated_documents",
                "ordering": ["-generated_at"],
            },
        ),
    ]
